# Use a Node.js image with Vite for development
FROM node:18 AS dev

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the React app source code
COPY . .

# Expose the Vite development port
EXPOSE 5173

# Set host and disable strict port for Vite
ENV VITE_API_URL=http://localhost:8080/employees
ENV HOST=0.0.0.0

# Start the Vite development server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]